In [3]:
# pip install numpy

In [4]:
import numpy as np

In [5]:
import time

In [6]:
a = list(range(10000000))
b = list(range(10000000))
start_time = time.perf_counter()
ans = [x + y for x , y in list(zip(a , b))]
end_time = time.perf_counter()
print("Time taken python : " , end_time - start_time)

Time taken python :  1.5633918999810703


In [7]:
a = np.array(a)
b = np.array(b)
start_time = time.perf_counter()
ans = a + b
end_time = time.perf_counter()
print("Time taken for Numpy : " , end_time - start_time)

Time taken for Numpy :  0.10694850003346801


### Creation of Arrays in Numpy

In [9]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
print(array)

[1 2 3 4 5]


In [10]:
print(type(array))

<class 'numpy.ndarray'>


In [13]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [14]:
print(type(matrix))

<class 'numpy.ndarray'>


In [16]:
arr_2 = np.array([1 , 2 , "hello"])
print(arr_2)
print(type(arr_2))

['1' '2' 'hello']
<class 'numpy.ndarray'>


In [18]:
array_3 = np.array([1, 2, 3, 4], dtype = np.int8)
print(array_3)
print(type(array_3))

[1 2 3 4]
<class 'numpy.ndarray'>


In [19]:
print(type(array_3[0]))

<class 'numpy.int8'>


In [20]:
print(type(array[0]))

<class 'numpy.int64'>


In [21]:
array_4 = np.array([1, 2, 3, "hello"])
print(array_4)

['1' '2' '3' 'hello']


In [24]:
array_5 = np.array([1, 2, 3, "hello"] , dtype = np.float64)
print(array_5)


ValueError: could not convert string to float: 'hello'

In [26]:
array_6 = np.array([1, 2, 3, "1000"] , dtype = np.float64)
print(array_6)
print(type(array_6))

[   1.    2.    3. 1000.]
<class 'numpy.ndarray'>


In [27]:
array_6

array([   1.,    2.,    3., 1000.])

In [28]:
print(matrix)

[[1 2 3]
 [4 5 6]]


In [32]:
print(matrix[0])

[1 2 3]


In [31]:
print(matrix[0][1])

2


In [33]:
list(range(1, 11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [34]:
list(range(1 , 11  , 2))

[1, 3, 5, 7, 9]

### np.arange(start, stop, step)

In [35]:
array = np.arange(1 , 11, 2)

In [37]:
print(array)
print(type(array))

[1 3 5 7 9]
<class 'numpy.ndarray'>


### np.linspace(start , stop , num = x)

In [39]:
np_linspace_1 = np.linspace(1 , 100 , 4)
print(np_linspace_1)
print(type(np_linspace_1))

[  1.  34.  67. 100.]
<class 'numpy.ndarray'>


In [40]:
np_linspace_2 = np.linspace(1 , 10 , 10)
print(np_linspace_2)
print(type(np_linspace_2))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [41]:
for num in np.linspace(1 , 10 , 10):
  print(num)
  print(type(num))
  print(type(int(num)))
  print("=================================")

1.0
<class 'numpy.float64'>
<class 'int'>
2.0
<class 'numpy.float64'>
<class 'int'>
3.0
<class 'numpy.float64'>
<class 'int'>
4.0
<class 'numpy.float64'>
<class 'int'>
5.0
<class 'numpy.float64'>
<class 'int'>
6.0
<class 'numpy.float64'>
<class 'int'>
7.0
<class 'numpy.float64'>
<class 'int'>
8.0
<class 'numpy.float64'>
<class 'int'>
9.0
<class 'numpy.float64'>
<class 'int'>
10.0
<class 'numpy.float64'>
<class 'int'>


### np.zeros(shape_of_matrix)

In [43]:
np_zeros_1 = np.zeros(5)
print(np_zeros_1)
print(type(np_zeros_1))

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [45]:
np_zeros_2 = np.zeros((5, 3))
print(np_zeros_2)
print(type(np_zeros_2))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [46]:
np_zeros_2.ndim

2

In [47]:
np_zeros_3 = np.zeros((5, 3, 2))
print(np_zeros_3)
print(type(np_zeros_3))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
<class 'numpy.ndarray'>


In [48]:
np_zeros_3.ndim

3

In [49]:
np_zeros_2.shape

(5, 3)

In [52]:
np_zeros_3.shape

(5, 3, 2)

### np.ones(shape)

In [53]:
a = np.ones((2 , 3))
print(a)
print(type(a))

[[1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>


### np.full(shape , fill_value)

In [54]:
b = np.full((2 , 3) , 15)
print(b)
print(type(b))

[[15 15 15]
 [15 15 15]]
<class 'numpy.ndarray'>


### np.eye(shape)

In [55]:
c = np.eye(5)
print(c)
print(type(c))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>


In [56]:
d = np.eye(2 , 3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]]


In [57]:
e = np.eye(3 ,2)
print(e)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [58]:
f = np.eye(7)
print(f)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
