### np.empty(shape)

In [1]:
import numpy as np
empty = np.empty((2 , 3))

In [2]:
print(empty)

[[0.00000000e+000 0.00000000e+000 1.08138329e-311]
 [1.08138329e-311 1.18575755e-322 8.89318163e-323]]


In [4]:
a = np.empty((2 , 3) , dtype= np.int8)
print(a)
print(type(a))

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>


In [5]:
import time
start = time.perf_counter()
ones = np.ones((5 , 5))
end = time.perf_counter()
time_taken = end - start
print("Time Taken : " , time_taken)

Time Taken :  7.219996768981218e-05


In [6]:
start = time.perf_counter()
ones = np.empty((5 , 5))
end = time.perf_counter()
time_taken = end - start
print("Time Taken : " , time_taken)

Time Taken :  4.320003790780902e-05


### np.random.rand(shape)

In [7]:
random = np.random.rand(2 , 3)
print(random)
print(type(random))

[[0.07903488 0.27230269 0.6832752 ]
 [0.40251947 0.82983689 0.079211  ]]
<class 'numpy.ndarray'>


In [8]:
random_1D = np.random.rand(9)
print(random_1D)
print(type(random_1D))

[0.81591682 0.1720762  0.7099589  0.1492361  0.88615054 0.42235239
 0.19011172 0.8127402  0.83847067]
<class 'numpy.ndarray'>


### Numpy Array Attributes

### ndarray.shape()

In [10]:
matrix = np.array([[1 , 2, 3] , [4 , 5 , 6]])
print(matrix)
print(matrix.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


### ndarray.ndim

In [11]:
matrix = np.array([[1, 2, 3],[4, 5, 6]])
print(matrix)
print(matrix.ndim)

[[1 2 3]
 [4 5 6]]
2


### ndarray.shape

In [13]:
matrix = np.array([[1 , 2 , 3] , [4 , 5, 6]])
print(matrix)
print(matrix.size)

[[1 2 3]
 [4 5 6]]
6


### ndarray.dtype

In [14]:
print(matrix.dtype)

int64


### ndarray.itemsize

In [15]:
print(matrix.itemsize)

8


ndarray.nbytes

In [16]:
print(matrix.nbytes)

48


### ndarray.T

In [19]:
print(matrix)  # 2 rows and 3 columns

[[1 2 3]
 [4 5 6]]


In [20]:
print(matrix.T) # 3 rows and 2 columns

[[1 4]
 [2 5]
 [3 6]]


### Array reshaping and resizing in numpy

#### reshape()

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)
print(arr.shape)
print(arr.ndim)

[1 2 3 4 5 6]
(6,)
1


In [ ]:
reshaped_1 = np.reshape(arr , (2 , 3))
print(reshaped_1)
print(reshaped_1.shape)
print(reshaped_1.ndim)


[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [24]:
reshaped_2 = np.reshape(arr , (2 , 3))
print(reshaped_2)
print(reshaped_2.shape)
print(reshaped_2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [25]:
reshaped_3 = np.reshape(arr , (1 , 6))
print(reshaped_3)
print(reshaped_3.shape)
print(reshaped_3.ndim)

[[1 2 3 4 5 6]]
(1, 6)
2


In [27]:
arr_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr_1.ndim)
print(arr_1.shape)

1
(12,)


In [28]:
arr_2 = np.reshape(arr_1, (3 , -1))
print(arr_2)
print(arr_2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [29]:
arr_3 = np.reshape(arr_1, (-1 , 4))
print(arr_3)
print(arr_3.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [30]:
arr_4 = np.reshape(arr_1, (-1 , -1))
print(arr_4)
print(arr_4.shape)

ValueError: can only specify one unknown dimension

In [31]:
arr_5 = np.reshape(arr_1, (7 , -1))
print(arr_5)
print(arr_5.shape)

ValueError: cannot reshape array of size 12 into shape (7,newaxis)