### ravel()

In [1]:
import numpy as np

In [2]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(array)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
array_ravel = array.ravel()
print(array_ravel)

[1 2 3 4 5 6 7 8]


In [4]:
print(id(array))
print(id(array.ravel()))
print(id(array_ravel))

2903566958736
2904078788112
2904078787824


In [6]:
print(f"Data address of 'a' :{array_ravel.__array_interface__['data'][0]}")

Data address of 'a' :2903518689008


In [7]:
print(f"Data address of 'a' :{array.__array_interface__['data'][0]}")

Data address of 'a' :2903518689008


In [9]:
print(array)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
array[0][0] = 11
print(array)

[[11  2  3  4]
 [ 5  6  7  8]]


In [11]:
print(array.ravel())

[11  2  3  4  5  6  7  8]


In [12]:
print(array.ravel().shape)

(8,)


### flatten()

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [15]:
print(f"Address of 'a' : {a.__array_interface__['data'][0]}")

Address of 'a' : 2903553730256


In [17]:
a_flatten = a.flatten()
print(a_flatten)

[1 2 3 4 5 6]


In [19]:
print(f"Address of 'a_flatten' : {a_flatten.__array_interface__['data'][0]}")

Address of 'a_flatten' : 2903553731920


### resize()

In [30]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [31]:

a.resize((3 ,3) , refcheck=False)

In [32]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

### squeeze()

In [33]:
a = np.array([[[1],[2],[3]]])
print(a)
print(a.shape)

[[[1]
  [2]
  [3]]]
(1, 3, 1)


In [34]:
b = np.squeeze(a)
print(b)
print(b.shape)

[1 2 3]
(3,)


### Indexing and Slicing in Numpy

In [35]:
a = np.array([10, 20, 30, 40 , 50])
print(a)

[10 20 30 40 50]


In [36]:
print(a[0])

10


In [37]:
print(a[-1])

50


In [38]:
print(a[4])

50


In [41]:
print(a)
print(a[1:4])

[10 20 30 40 50]
[20 30 40]


In [42]:
print(a[1:-1])

[20 30 40]


In [43]:
print(a[0:3])

[10 20 30]


In [44]:
print(a[:3])

[10 20 30]


In [45]:
print(a[2:])

[30 40 50]


In [46]:
print(a[::2])

[10 30 50]


In [47]:
print(a[::-1])

[50 40 30 20 10]


In [48]:
list_a = [1, 2, 3, 4, 5]
print(list_a[::-1])

[5, 4, 3, 2, 1]


### Indexing in 2D Arrays

In [49]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [50]:
print(matrix[0][1])

2


In [51]:
print(matrix[0, 1])

2


In [52]:
print(matrix[: , 2])

[3 6]


In [53]:
print(matrix)

[[1 2 3]
 [4 5 6]]


In [58]:
print(matrix[0:2 , 1:])

[[2 3]
 [5 6]]


In [59]:
print(matrix[::-1, ::-1])

[[6 5 4]
 [3 2 1]]


### Boolean Indexing

In [60]:
a = np.array([5, 10, 15, 20, 25])
print(a)

[ 5 10 15 20 25]


In [63]:
print([a > 15])

[array([False, False, False,  True,  True])]


In [64]:
print(a[a > 15])

[20 25]


### Fancy Indexing

In [65]:
a = np.array([100, 200, 300, 400, 500])
print(a)

[100 200 300 400 500]


In [67]:
indices = [0, 2, 4]
print(a[indices])

[100 300 500]


In [1]:
import numpy as np

In [2]:
mat = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
mat [ mat > 5]

array([6, 7, 8, 9])

In [4]:
mat[[0, 1], [2, 2]]

array([3, 6])

### Modifying with indexing

In [5]:
arr = np.array([1, 2, 3, 4])
arr[2] = 100
print(arr)

[  1   2 100   4]


In [6]:
arr[arr > 2] = 2000
print(arr)

[   1    2 2000 2000]


### Indexing with np.where()

In [7]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr)

[10 20 30 40 50 60]


In [8]:
idx = np.where(arr > 20)
print(idx)

(array([2, 3, 4, 5]),)
