### Mathematical Operations

In [1]:
import numpy as np

In [2]:
list_a = [1, 2, 3, 4]
list_b = [5, 6, 7, 8]

print(list_a + list_b)

[1, 2, 3, 4, 5, 6, 7, 8]


In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(a + b)

[ 6  8 10 12]


In [4]:
print(a * b)

[ 5 12 21 32]


In [5]:
print(a - b)

[-4 -4 -4 -4]


In [6]:
print(a / b)

[0.2        0.33333333 0.42857143 0.5       ]


In [7]:
print(a * b)

[ 5 12 21 32]


In [9]:
print(np.dot(a, b))

70


In [14]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2], [3, 4]])

In [15]:
print(np.dot(a, b))

[[ 7 10]
 [15 22]]


In [16]:
a = np.array([[1, 2, 3], [3, 4, 2]])
b = np.array([[1, 2, 1], [3, 4, 1]])

In [ ]:
print(np.dot(a , b))

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [18]:
print(np.dot(a.T , b))

[[10 14  4]
 [14 20  6]
 [ 9 14  5]]


In [19]:
print(np.dot(a , b.T))

[[ 8 14]
 [13 27]]


### Aggregrate Operations

In [43]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [21]:
print(np.sum(a))

36


In [22]:
print(np.min(a))

1


In [24]:
print(np.max(a))

8


In [25]:
print(np.argmax(a))

7


In [26]:
print(np.argmin(a))

0


In [28]:
print(np.sum(a , axis = 0))

[ 6  8 10 12]


In [29]:
print(np.sum(a , axis = 1))

[10 26]


In [30]:
print(np.mean(a))

4.5


In [31]:
print(np.mean(a , axis = 0))

[3. 4. 5. 6.]


In [32]:
print(np.mean(a , axis = 1))

[2.5 6.5]


In [34]:
print(np.std(a))

2.29128784747792


In [35]:
print(np.std(a, axis = 1))

[1.11803399 1.11803399]


In [36]:
print(np.std(a , axis = 0))

[2. 2. 2. 2.]


In [37]:
print(np.cumsum([1, 2, 3, 4]))

[ 1  3  6 10]


In [39]:
a = np.array([1 , 2, 3])
b = np.array([4 , 5, 6])
print(a@b)

32


In [48]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [49]:
print(np.median(a))

4.5


In [50]:
print(np.median(a , axis = 0))

[3. 4. 5. 6.]


In [52]:
print(np.median(a, axis = 1))

[2.5 6.5]


In [54]:
print(np.var(a))

5.25


In [55]:
print(np.var(a, axis = 1))

[1.25 1.25]


In [57]:
print(np.var(a, axis = 0))

[4. 4. 4. 4.]


In [58]:
data = np.array([1, 3, 5, 7, 9])
print(np.percentile(data, 50))

5.0


### Sort Search and Counting functions

In [60]:
a = np.array([3, 6, 1, 1, 1, 1, 8, 2, 5, 6])
print(a)

[3 6 1 1 1 1 8 2 5 6]


In [61]:
print(np.sort(a))

[1 1 1 1 2 3 5 6 6 8]


In [62]:
print(np.argsort(a))

[3 2 5 4 7 0 8 1 9 6]


In [63]:
print(len(a))

10


In [64]:
print(np.searchsorted(np.sort(a), 4))

6


In [65]:
print(np.unique(a))

[1 2 3 5 6 8]


In [66]:
print(np.bincount(a))

[0 4 1 1 0 1 2 0 1]


In [67]:
a = np.array([1.2 , 4, 6, 8, 1, 1, 3, 5])
print(np.bincount(a))

TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

In [68]:
arr = np.array([1, 2, 3, 4])
for x in arr:
  print(x)

1
2
3
4


In [69]:
a = np.array([[1, 2, 3], [4, 5, 6]])
for a in a:
  print(a)

[1 2 3]
[4 5 6]


In [70]:
list(range(11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [71]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [77]:
arr = np.arange(8).reshape(2, 2, 2)
print(arr)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [75]:
np.arange(8).reshape(2, 4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [79]:
print(arr.ndim)

3


In [80]:
for x in np.nditer(arr):
  print(x)

0
1
2
3
4
5
6
7


In [81]:
a = np.array([1, 2, 3, 4])
b = a
print(id(a))
print(id(b))

2838332256304
2838332256304


In [82]:
b[0] = 23
print(a)
print(b)

[23  2  3  4]
[23  2  3  4]


In [83]:
c = np.array([5, 6, 7, 8])
d = c.copy()
print(id(c))
print(id(d))

2838332260144
2838332258608


In [84]:
d[0] = 101
print(d)
print(c)

[101   6   7   8]
[5 6 7 8]


In [86]:
a = np.array([1, 2, 3, 4])
b = a.view()

print(id(a))
print(id(b))

2838335543152
2838335544112


In [87]:
print(np.shares_memory(a, b))

True


In [88]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])
print(a)
print(b)

[[1 2]]
[[3 4]]


In [90]:
print(np.vstack((a , b)))

[[1 2]
 [3 4]]


In [91]:
print(np.hstack((a , b)))

[[1 2 3 4]]


### numpy chars and strings

#### 1. np.char.add()

In [94]:
a = np.array(['hello ' , 'manoj '])
b = np.array(['world' , 'babu'])


In [95]:
print(np.char.add(a , b))

['hello world' 'manoj babu']


In [96]:
print(np.char.multiply(a , 2))

['hello hello ' 'manoj manoj ']


In [97]:
print(np.char.upper(b))

['WORLD' 'BABU']


In [98]:
print(np.char.lower(a))

['hello ' 'manoj ']


In [99]:
print(np.char.capitalize(a))

['Hello ' 'Manoj ']


In [101]:
print(np.char.center(b , 11 , fillchar = "*"))

['***world***' '****babu***']


In [103]:
a = np.array(["hello__" , "world__"])
print(a)

['hello__' 'world__']


In [106]:
print(np.char.replace(a, "__" , ""))

['hello' 'world']


In [107]:
a = np.array(["data_science" , "machine_learning"])
print(np.char.split(a , sep="_"))

[list(['data', 'science']) list(['machine', 'learning'])]


In [108]:
print(np.char.find(a, "learn"))

[-1  8]


In [109]:
print(np.char.count(a, "learn"))

[0 1]
