### Mathematical Operations

In [1]:
import numpy as np

In [3]:
list_a = [1, 2, 3, 4]
list_b = [5, 6, 7, 8]

print(list_a + list_b)

[1, 2, 3, 4, 5, 6, 7, 8]


In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(a + b)

[ 6  8 10 12]


In [5]:
print(a * b)

[ 5 12 21 32]


In [6]:
print(a - b)

[-4 -4 -4 -4]


In [7]:
print(a / b)

[0.2        0.33333333 0.42857143 0.5       ]
